# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "4.3"
    - nodejs_version: "5.6"
  JSPM_GITHUB_AUTH_TOKEN: "Qm9ybnRyYWVnZXJNYXJjOmUyYjBiZGU2ZGQyYTMwOWE0ODQ0MDFmMGM5YTQ3YzZhYTE4YWY3Mjk="

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@3
  - npm install -g jspm
  - jspm config registries.github.auth %JSPM_GITHUB_AUTH_TOKEN%
  - jspm config registries.github.maxRepoSize 0
  - jspm registry export github #output to see what the registry looks like


build_script:
  - npm run setup

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - git --version
  - jspm --version
  - cmd: npm run eslint
  - cmd: npm run test
  - cmd: npm run test-e2e

# Set build version format here instead of in the admin panel.
version: "{build}"
